#!/bin/sh
#
# @name Torpedo-Shaped AUV
#
# @type AUV
# @class Underwater Robot
#
# @maintainer Pedro Boada <pedro.boada@pucp.pe>
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.auv_defaults

# Configuration of the Control Allocator (CA) for the AUV
param set-default CA_AIRFRAME 8       # Unique ID for your AUV
param set-default CA_ROTOR_COUNT 5    # Total number of thrusters (2 horizontal, 2 vertical, 1 yaw thruster)

# Configuration for thruster 0 (Horizontal 1 - Surge Direction)
param set-default CA_ROTOR0_AX 1
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX 0.5    # Position on the X-axis (front)
param set-default CA_ROTOR0_PY 0.2    # Position on the Y-axis (lateral)
param set-default CA_ROTOR0_PZ 0      # Position on the Z-axis

# Configuration for thruster 1 (Horizontal 2 - Surge Direction)
param set-default CA_ROTOR1_AX 1
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ 0
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PX 0.5    # Position on the X-axis (front)
param set-default CA_ROTOR1_PY -0.2   # Position on the Y-axis (opposite lateral)
param set-default CA_ROTOR1_PZ 0      # Position on the Z-axis

# Configuration for thruster 2 (Vertical 1 - Heave Direction)
param set-default CA_ROTOR2_AX 0
param set-default CA_ROTOR2_AY 0
param set-default CA_ROTOR2_AZ 1
param set-default CA_ROTOR2_KM 0
param set-default CA_ROTOR2_PX 0.3    # Position on the X-axis
param set-default CA_ROTOR2_PY 0.2    # Position on the Y-axis
param set-default CA_ROTOR2_PZ 0.2    # Position on the Z-axis (upper)

# Configuration for thruster 3 (Vertical 2 - Heave Direction)
param set-default CA_ROTOR3_AX 0
param set-default CA_ROTOR3_AY 0
param set-default CA_ROTOR3_AZ 1
param set-default CA_ROTOR3_KM 0
param set-default CA_ROTOR3_PX 0.3    # Position on the X-axis
param set-default CA_ROTOR3_PY -0.2   # Position on the Y-axis (opposite lateral)
param set-default CA_ROTOR3_PZ 0.2    # Position on the Z-axis (upper)

# Configuration for thruster 4 (Yaw Thruster)
param set-default CA_ROTOR4_AX 0
param set-default CA_ROTOR4_AY 0
param set-default CA_ROTOR4_AZ 0
param set-default CA_ROTOR4_KM 1      # Torque for changing the yaw direction
param set-default CA_ROTOR4_PX 0.6    # Position on the X-axis (near the front)
param set-default CA_ROTOR4_PY 0      # Position on the Y-axis (centered)
param set-default CA_ROTOR4_PZ 0.1    # Position on the Z-axis

# Configuration of the rear control surfaces
# Note: Control surfaces are not typically configured directly in this file. Instead, they will be handled by mixers and attitude controllers.

# Configure other specific parameters for the AUV
param set-default NAV_DEPTH_HOLD 1  # Enable depth control

# Reference the mixer file
set MIXER auv_torpedo

# Indicate the startup mode
echo "Torpedo-shaped AUV configuration loaded successfully"
